<?xml version="1.0" encoding="utf-8"?><Database Name="bibliotek" Class="BibAnotherChanceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=anatoly.mine.nu;Initial Catalog=bibliotek;Persist Security Info=True;User ID=bibliotek" SettingsObjectName="Biblan.Properties.Settings" SettingsPropertyName="bibliotekConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.usp_add_book" Method="usp_add_book">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <Parameter Name="title" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="number_of_pages" Type="System.Int32" DbType="Int" />
    <Parameter Name="print_year" Type="System.Int32" DbType="Int" />
    <Parameter Name="publisher" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="author" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_update_customer" Method="usp_update_customer">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_add_copy" Method="usp_add_copy">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_add_customer" Method="usp_add_customer">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Parameter Name="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="phone" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_borrow_book" Method="usp_borrow_book">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <Parameter Name="customerID" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="copyID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_delete_customer" Method="usp_delete_customer">
    <Parameter Name="customerID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_return_book" Method="usp_return_book">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <Parameter Name="customerID" Type="System.String" DbType="VarChar(75)" />
    <Parameter Name="copyID" Type="System.Int32" DbType="Int" />
    <Parameter Name="bdate" Type="System.DateTime" DbType="DateTime" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.usp_test_insert" Method="usp_test_insert">
    <Parameter Name="temp" Type="System.String" DbType="VarChar(10)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.get_available_copies_for_a_book" Method="get_available_copies_for_a_book" IsComposable="true">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <ElementType Name="get_available_copies_for_a_bookResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="CopyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.test_get_all" Method="test_get_all" IsComposable="true">
    <ElementType Name="test_get_allResult">
      <Column Name="test" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_copies_for_a_book" Method="get_copies_for_a_book" IsComposable="true">
    <Parameter Name="isbn" Type="System.String" DbType="VarChar(35)" />
    <ElementType Name="get_copies_for_a_bookResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="CopyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_last_book_borrowed" Method="get_last_book_borrowed" IsComposable="true">
    <ElementType Name="get_last_book_borrowedResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="NumberOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_book_print_year" Method="search_book_print_year" IsComposable="true">
    <ElementType Name="search_book_print_yearResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="NumberOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_books_titles" Method="search_books_titles" IsComposable="true">
    <Parameter Name="title" Type="System.String" DbType="VarChar(75)" />
    <ElementType Name="search_books_titlesResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="NumberOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_books_with_a_title_that_begins_with_A" Method="search_books_with_a_title_that_begins_with_A" IsComposable="true">
    <ElementType Name="search_books_with_a_title_that_begins_with_AResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="NumberOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_customers_with_more_than_one_book" Method="search_customers_with_more_than_one_book" IsComposable="true">
    <ElementType Name="search_customers_with_more_than_one_bookResult">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NumberOf" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.search_number_of_book_pages" Method="search_number_of_book_pages" IsComposable="true">
    <ElementType Name="search_number_of_book_pagesResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="NumberOfPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_all_customers" Method="get_all_customers" IsComposable="true">
    <ElementType Name="get_all_customersResult">
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="VarChar(75)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_all_borrows" Method="get_all_borrows" IsComposable="true">
    <ElementType Name="get_all_borrowsResult">
      <Column Name="ISBN" Type="System.String" DbType="VarChar(35) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CopyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>